### ISSUE TITLE
error when fetching information for `graphql-pro`

### ISSUE THREAD

**Issue by dimerman** [bmulholland/bundler-audited_update#4]
for the url `https://rubygems.org/api/v2/rubygems/graphql-pro/versions/1.21.1`

```
/Users/dan/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/open-uri.rb:364:in `open_http': 404 Not Found (OpenURI::HTTPError)
	from /Users/dan/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/open-uri.rb:741:in `buffer_open'
	from /Users/dan/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/open-uri.rb:212:in `block in open_loop'
	from /Users/dan/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/open-uri.rb:210:in `catch'
	from /Users/dan/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/open-uri.rb:210:in `open_loop'
	from /Users/dan/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/open-uri.rb:151:in `open_uri'
	from /Users/dan/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/open-uri.rb:721:in `open'
	from /Users/dan/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/open-uri.rb:729:in `read'
	from /Users/dan/.rvm/gems/ruby-3.0.3@recital-backend/gems/bundler-audited_update-0.2.0/lib/bundler/audited_update.rb:236:in `gem_info'
	from /Users/dan/.rvm/gems/ruby-3.0.3@recital-backend/gems/bundler-audited_update-0.2.0/lib/bundler/audited_update.rb:74:in `gem_output'
	from /Users/dan/.rvm/gems/ruby-3.0.3@recital-backend/gems/bundler-audited_update-0.2.0/lib/bundler/audited_update.rb:66:in `block in output_changed_gems_section'
	from /Users/dan/.rvm/gems/ruby-3.0.3@recital-backend/gems/bundler-audited_update-0.2.0/lib/bundler/audited_update.rb:66:in `each'
	from /Users/dan/.rvm/gems/ruby-3.0.3@recital-backend/gems/bundler-audited_update-0.2.0/lib/bundler/audited_update.rb:66:in `output_changed_gems_section'
	from /Users/dan/.rvm/gems/ruby-3.0.3@recital-backend/gems/bundler-audited_update-0.2.0/lib/bundler/audited_update.rb:57:in `output_changed_gems'
	from /Users/dan/.rvm/gems/ruby-3.0.3@recital-backend/gems/bundler-audited_update-0.2.0/lib/bundler/audited_update.rb:24:in `run!'
	from /Users/dan/.rvm/gems/ruby-3.0.3@recital-backend/gems/bundler-audited_update-0.2.0/bin/audited_bundle_update:5:in `<top (required)>'
	from /Users/dan/.rvm/gems/ruby-3.0.3@recital-backend/bin/audited_bundle_update:25:in `load'
	from /Users/dan/.rvm/gems/ruby-3.0.3@recital-backend/bin/audited_bundle_update:25:in `<main>'
	from /Users/dan/.rvm/rubies/ruby-3.0.3/bin/ruby_executable_hooks:22:in `eval'
	from /Users/dan/.rvm/rubies/ruby-3.0.3/bin/ruby_executable_hooks:22:in `<main>'
rake aborted!

```

**Comment by bmulholland** [comment]
Probably actually a bug with private packages

**Comment by bmulholland** [comment]
Fixed
